<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Decimal\\' => array($vendorDir . '/php-decimal/php-decimal/src', $vendorDir . '/php-decimal/stubs'),
);
