<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita566d41a2c67ed3afc3bf81f945cf0b4
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Decimal\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Decimal\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-decimal/php-decimal/src',
            1 => __DIR__ . '/..' . '/php-decimal/stubs',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita566d41a2c67ed3afc3bf81f945cf0b4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita566d41a2c67ed3afc3bf81f945cf0b4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
