<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Web3p\\RLP\\' => array($vendorDir . '/web3p/rlp/src'),
);
